spring:
  application:
    name: freelancehub

  datasource:
    url: jdbc:postgresql://localhost:5432/freelancehub
    username: freelancehub
    password: freelancehub123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080